"""Updated models to include menu_item_image in OrderItem

Revision ID: daffbdcc990c
Revises: 1e9d83d720e1
Create Date: 2024-07-18 16:02:33.227411

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'daffbdcc990c'
down_revision = '1e9d83d720e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('menu_item_image', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.drop_column('menu_item_image')

    # ### end Alembic commands ###
