"""added an attribute

Revision ID: ff1481791db7
Revises: daffbdcc990c
Create Date: 2024-07-19 00:52:49.556734

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff1481791db7'
down_revision = 'daffbdcc990c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order_no', sa.String(length=80), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('order_no')

    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
